const botaoAlterarTema = document.getElementById("botao-alterar-tema");
const body = document.querySelector("body");
const imagemBotaoTrocaDeTema = document.querySelector(".imagem-botao")
const imagemPokebola = document.querySelector(".pokebola")
const imagemLogo = document.querySelector(".logo")

const bulbasaur = document.querySelector(".gif-bulbasaur")
const ivysaur = document.querySelector(".gif-ivysaur")
const venusaur = document.querySelector(".gif-venusaur")
const charmander = document.querySelector(".gif-charmander")
const charmeleon = document.querySelector(".gif-charmeleon")
const charizard = document.querySelector(".gif-charizard")
const squirtle = document.querySelector(".gif-squirtle")
const wartortle = document.querySelector(".gif-wartortle")
const blastoise = document.querySelector(".gif-blastoise")
const caterpie = document.querySelector(".gif-caterpie")
const metapod = document.querySelector(".gif-metapod")
const butterfree = document.querySelector(".gif-butterfree")
const weedle = document.querySelector(".gif-weedle")
const kakuna = document.querySelector(".gif-kakuna")
const beedrill = document.querySelector(".gif-beedrill")
const pidgey = document.querySelector(".gif-pidgey")
const pidgeotto = document.querySelector(".gif-pidgeotto")
const pidgeot = document.querySelector(".gif-pidgeot")
const rattata = document.querySelector(".gif-rattata")
const raticate = document.querySelector(".gif-raticate")
const spearow = document.querySelector(".gif-spearow")
const fearow = document.querySelector(".gif-fearow")
const ekans = document.querySelector(".gif-ekans")
const arbok = document.querySelector(".gif-arbok")
const pikachu = document.querySelector(".gif-pikachu")
const raichu = document.querySelector(".gif-raichu")
const sandshrew = document.querySelector(".gif-sandshrew")
const sandslash = document.querySelector(".gif-sandslash")
const nidoranfemea = document.querySelector(".gif-nidoran-femea")
const nidorina = document.querySelector(".gif-nidorina")
const nidoqueen = document.querySelector(".gif-nidoqueen")
const nidoranmacho = document.querySelector(".gif-nidoran-macho")
const nidorino = document.querySelector(".gif-nidorino")
const nidoking = document.querySelector(".gif-nidoking")
const clefairy = document.querySelector(".gif-clefairy")
const clefable = document.querySelector(".gif-clefable")
const vulpix = document.querySelector(".gif-vulpix")
const ninetales = document.querySelector(".gif-ninetales")
const jigglypuff = document.querySelector(".gif-jigglypuff")
const wigglytuff = document.querySelector(".gif-wigglytuff")
const zubat = document.querySelector(".gif-zubat")
const golbat = document.querySelector(".gif-golbat")
const oddish = document.querySelector(".gif-oddish")
const gloom = document.querySelector(".gif-gloom")
const vileplume = document.querySelector(".gif-vileplume")
const paras = document.querySelector(".gif-paras")
const parasect = document.querySelector(".gif-parasect")
const venonat = document.querySelector(".gif-venonat")
const venomoth = document.querySelector(".gif-venomoth")
const diglett = document.querySelector(".gif-diglett")
const dugtrio = document.querySelector(".gif-dugtrio")
const meowth = document.querySelector(".gif-meowth")
const persian = document.querySelector(".gif-persian")
const psyduck = document.querySelector(".gif-psyduck")
const golduck = document.querySelector(".gif-golduck")
const mankey = document.querySelector(".gif-mankey")
const primeape = document.querySelector(".gif-primeape")
const growlithe = document.querySelector(".gif-growlithe")
const arcanine = document.querySelector(".gif-arcanine")
const poliwag = document.querySelector(".gif-poliwag")
const poliwhirl = document.querySelector(".gif-poliwhirl")
const poliwrath = document.querySelector(".gif-poliwrath")
const abra = document.querySelector(".gif-abra")
const kadabra = document.querySelector(".gif-kadabra")
const alakazam = document.querySelector(".gif-alakazam")
const machop = document.querySelector(".gif-machop")
const machoke = document.querySelector(".gif-machoke")
const machamp = document.querySelector(".gif-machamp")
const bellsprout = document.querySelector(".gif-bellsprout")
const weepinbell = document.querySelector(".gif-weepinbell")
const victreebel = document.querySelector(".gif-victreebel")
const tentacool = document.querySelector(".gif-tentacool")
const tentacruel = document.querySelector(".gif-tentacruel")
const geodude = document.querySelector(".gif-geodude")
const graveler = document.querySelector(".gif-graveler")
const golem = document.querySelector(".gif-golem")
const ponyta = document.querySelector(".gif-ponyta")
const rapidash = document.querySelector(".gif-rapidash")
const slowpoke = document.querySelector(".gif-slowpoke")
const slowbro = document.querySelector(".gif-slowbro")
const magnemite = document.querySelector(".gif-magnemite")
const magneton = document.querySelector(".gif-magneton")
const farfetchd = document.querySelector(".gif-farfetchd")
const doduo = document.querySelector(".gif-doduo")
const dodrio = document.querySelector(".gif-dodrio")
const seel = document.querySelector(".gif-seel")
const dewgong = document.querySelector(".gif-dewgong")
const grimer = document.querySelector(".gif-grimer")
const muk = document.querySelector(".gif-muk")
const shellder = document.querySelector(".gif-shellder")
const cloyster = document.querySelector(".gif-cloyster")
const gastly = document.querySelector(".gif-gastly")
const haunter = document.querySelector(".gif-haunter")
const gengar = document.querySelector(".gif-gengar")
const onix = document.querySelector(".gif-onix")
const drowzee = document.querySelector(".gif-drowzee")
const hypno = document.querySelector(".gif-hypno")
const krabby = document.querySelector(".gif-krabby")
const kingler = document.querySelector(".gif-kingler")
const voltorb = document.querySelector(".gif-voltorb")
const electrode = document.querySelector(".gif-electrode")
const exeggcute = document.querySelector(".gif-exeggcute")
const exeggutor = document.querySelector(".gif-exeggutor")
const cubone = document.querySelector(".gif-cubone")
const marowak = document.querySelector(".gif-marowak")
const hitmonlee = document.querySelector(".gif-hitmonlee")
const hitmonchan = document.querySelector(".gif-hitmonchan")
const lickitung = document.querySelector(".gif-lickitung")
const koffing = document.querySelector(".gif-koffing")
const weezing = document.querySelector(".gif-weezing")
const rhyhorn = document.querySelector(".gif-rhyhorn")
const rhydon = document.querySelector(".gif-rhydon")
const chansey = document.querySelector(".gif-chansey")
const tangela = document.querySelector(".gif-tangela")
const kangaskhan = document.querySelector(".gif-kangaskhan")
const horsea = document.querySelector(".gif-horsea")
const seadra = document.querySelector(".gif-seadra")
const goldeen = document.querySelector(".gif-goldeen")
const seaking = document.querySelector(".gif-seaking")
const staryu = document.querySelector(".gif-staryu")
const starmie = document.querySelector(".gif-starmie")
const mrmime = document.querySelector(".gif-mr-mime")
const scyther = document.querySelector(".gif-scyther")
const jynx = document.querySelector(".gif-jynx")
const electabuzz = document.querySelector(".gif-electabuzz")
const magmar = document.querySelector(".gif-magmar")
const pinsir = document.querySelector(".gif-pinsir")
const tauros = document.querySelector(".gif-tauros")
const magikarp = document.querySelector(".gif-magikarp")
const gyarados = document.querySelector(".gif-gyarados")
const lapras = document.querySelector(".gif-lapras")
const ditto = document.querySelector(".gif-ditto")
const eevee = document.querySelector(".gif-eevee")
const vaporeon = document.querySelector(".gif-vaporeon")
const jolteon = document.querySelector(".gif-jolteon")
const flareon = document.querySelector(".gif-flareon")
const porygon = document.querySelector(".gif-porygon")
const omanyte = document.querySelector(".gif-omanyte")
const omastar = document.querySelector(".gif-omastar")
const kabuto = document.querySelector(".gif-kabuto")
const kabutops = document.querySelector(".gif-kabutops")
const aerodactyl = document.querySelector(".gif-aerodactyl")
const snorlax = document.querySelector(".gif-snorlax")
const articuno = document.querySelector(".gif-articuno")
const zapdos = document.querySelector(".gif-zapdos")
const moltres = document.querySelector(".gif-moltres")
const dratini = document.querySelector(".gif-dratini")
const dragonair = document.querySelector(".gif-dragonair")
const dragonite = document.querySelector(".gif-dragonite")
const mewtwo = document.querySelector(".gif-mewtwo")
const mew = document.querySelector(".gif-mew")

botaoAlterarTema.addEventListener("click", () => {

    const modoEscuroEstaAtivo = body.classList.contains("modo-escuro");

    body.classList.toggle("modo-escuro");

    if(modoEscuroEstaAtivo){

        imagemBotaoTrocaDeTema.setAttribute("src", "./src/imagens/sun.png")
        imagemPokebola.setAttribute("src", "./src/imagens/pokeball.png")
        imagemLogo.setAttribute("src", "./src/imagens/logo.png")
       
        bulbasaur.setAttribute("src", "./src/imagens/bulbasaur.gif")
        ivysaur.setAttribute("src", "./src/imagens/ivysaur.gif")
        venusaur.setAttribute("src", "./src/imagens/venusaur.gif")
        charmander.setAttribute("src", "./src/imagens/charmander.gif")
        charmeleon.setAttribute("src", "./src/imagens/charmeleon.gif")
        charizard.setAttribute("src", "./src/imagens/charizard.gif")
        squirtle.setAttribute("src", "./src/imagens/squirtle.gif")
        wartortle.setAttribute("src", "./src/imagens/wartortle.gif")
        blastoise.setAttribute("src", "./src/imagens/blastoise.gif")
        caterpie.setAttribute("src", "./src/imagens/caterpie.gif")
        metapod.setAttribute("src", "./src/imagens/metapod.gif")
        butterfree.setAttribute("src", "./src/imagens/butterfree.gif")
        weedle.setAttribute("src", "./src/imagens/weedle.gif")
        kakuna.setAttribute("src", "./src/imagens/kakuna.gif")
        beedrill.setAttribute("src", "./src/imagens/beedrill.gif")
        pidgey.setAttribute("src", "./src/imagens/pidgey.gif")
        pidgeotto.setAttribute("src", "./src/imagens/pidgeotto.gif")
        pidgeot.setAttribute("src", "./src/imagens/pidgeot.gif")
        rattata.setAttribute("src", "./src/imagens/rattata.gif")
        raticate.setAttribute("src", "./src/imagens/raticate.gif")
        spearow.setAttribute("src", "./src/imagens/spearow.gif")
        fearow.setAttribute("src", "./src/imagens/fearow.gif")
        ekans.setAttribute("src", "./src/imagens/ekans.gif")
        arbok.setAttribute("src", "./src/imagens/arbok.gif")
        pikachu.setAttribute("src", "./src/imagens/pikachu.gif")
        raichu.setAttribute("src", "./src/imagens/raichu.gif")
        sandshrew.setAttribute("src", "./src/imagens/sandshrew.gif")
        sandslash.setAttribute("src", "./src/imagens/sandslash.gif")
        nidoranfemea.setAttribute("src", "./src/imagens/nidoran-femea.gif")
        nidorina.setAttribute("src", "./src/imagens/nidorina.gif")
        nidoqueen.setAttribute("src", "./src/imagens/nidoqueen.gif")
        nidoranmacho.setAttribute("src", "./src/imagens/nidoran-macho.gif")
        nidorino.setAttribute("src", "./src/imagens/nidorino.gif")
        nidoking.setAttribute("src", "./src/imagens/nidoking.gif")
        clefairy.setAttribute("src", "./src/imagens/clefairy.gif")
        clefable.setAttribute("src", "./src/imagens/clefable.gif")
        vulpix.setAttribute("src", "./src/imagens/vulpix.gif")
        ninetales.setAttribute("src", "./src/imagens/ninetales.gif")
        jigglypuff.setAttribute("src", "./src/imagens/jigglypuff.gif")
        wigglytuff.setAttribute("src", "./src/imagens/wigglytuff.gif")
        zubat.setAttribute("src", "./src/imagens/zubat.gif")
        golbat.setAttribute("src", "./src/imagens/golbat.gif")
        oddish.setAttribute("src", "./src/imagens/oddish.gif")
        gloom.setAttribute("src", "./src/imagens/gloom.gif")
        vileplume.setAttribute("src", "./src/imagens/vileplume.gif")
        paras.setAttribute("src", "./src/imagens/paras.gif")
        parasect.setAttribute("src", "./src/imagens/parasect.gif")
        venonat.setAttribute("src", "./src/imagens/venonat.gif")
        venomoth.setAttribute("src", "./src/imagens/venomoth.gif")
        diglett.setAttribute("src", "./src/imagens/diglett.gif")
        dugtrio.setAttribute("src", "./src/imagens/dugtrio.gif")
        meowth.setAttribute("src", "./src/imagens/meowth.gif")
        persian.setAttribute("src", "./src/imagens/persian.gif")
        psyduck.setAttribute("src", "./src/imagens/psyduck.gif")
        golduck.setAttribute("src", "./src/imagens/golduck.gif")
        mankey.setAttribute("src", "./src/imagens/mankey.gif")
        primeape.setAttribute("src", "./src/imagens/primeape.gif")
        growlithe.setAttribute("src", "./src/imagens/growlithe.gif")
        arcanine.setAttribute("src", "./src/imagens/arcanine.gif")
        poliwag.setAttribute("src", "./src/imagens/poliwag.gif")
        poliwhirl.setAttribute("src", "./src/imagens/poliwhirl.gif")
        poliwrath.setAttribute("src", "./src/imagens/poliwrath.gif")
        abra.setAttribute("src", "./src/imagens/abra.gif")
        kadabra.setAttribute("src", "./src/imagens/kadabra.gif")
        alakazam.setAttribute("src", "./src/imagens/alakazam.gif")
        machop.setAttribute("src", "./src/imagens/machop.gif")
        machoke.setAttribute("src", "./src/imagens/machoke.gif")
        machamp.setAttribute("src", "./src/imagens/machamp.gif")
        bellsprout.setAttribute("src", "./src/imagens/bellsprout.gif")
        weepinbell.setAttribute("src", "./src/imagens/weepinbell.gif")
        victreebel.setAttribute("src", "./src/imagens/victreebel.gif")
        tentacool.setAttribute("src", "./src/imagens/tentacool.gif")
        tentacruel.setAttribute("src", "./src/imagens/tentacruel.gif")
        geodude.setAttribute("src", "./src/imagens/geodude.gif")
        graveler.setAttribute("src", "./src/imagens/graveler.gif")
        golem.setAttribute("src", "./src/imagens/golem.gif")
        ponyta.setAttribute("src", "./src/imagens/ponyta.gif")
        rapidash.setAttribute("src", "./src/imagens/rapidash.gif")
        slowpoke.setAttribute("src", "./src/imagens/slowpoke.gif")
        slowbro.setAttribute("src", "./src/imagens/slowbro.gif")
        magnemite.setAttribute("src", "./src/imagens/magnemite.gif")
        magneton.setAttribute("src", "./src/imagens/magneton.gif")
        farfetchd.setAttribute("src", "./src/imagens/farfetchd.gif")
        doduo.setAttribute("src", "./src/imagens/doduo.gif")
        dodrio.setAttribute("src", "./src/imagens/dodrio.gif")
        seel.setAttribute("src", "./src/imagens/seel.gif")
        dewgong.setAttribute("src", "./src/imagens/dewgong.gif")
        grimer.setAttribute("src", "./src/imagens/grimer.gif")
        muk.setAttribute("src", "./src/imagens/muk.gif")
        shellder.setAttribute("src", "./src/imagens/shellder.gif")
        cloyster.setAttribute("src", "./src/imagens/cloyster.gif")
        gastly.setAttribute("src", "./src/imagens/gastly.gif")
        haunter.setAttribute("src", "./src/imagens/haunter.gif")
        gengar.setAttribute("src", "./src/imagens/gengar.gif")
        onix.setAttribute("src", "./src/imagens/onix.gif")
        drowzee.setAttribute("src", "./src/imagens/drowzee.gif")
        hypno.setAttribute("src", "./src/imagens/hypno.gif")
        krabby.setAttribute("src", "./src/imagens/krabby.gif")
        kingler.setAttribute("src", "./src/imagens/kingler.gif")
        voltorb.setAttribute("src", "./src/imagens/voltorb.gif")
        electrode.setAttribute("src", "./src/imagens/electrode.gif")
        exeggcute.setAttribute("src", "./src/imagens/exeggcute.gif")
        exeggutor.setAttribute("src", "./src/imagens/exeggutor.gif")
        cubone.setAttribute("src", "./src/imagens/cubone.gif")
        marowak.setAttribute("src", "./src/imagens/marowak.gif")
        hitmonlee.setAttribute("src", "./src/imagens/hitmonlee.gif")
        hitmonchan.setAttribute("src", "./src/imagens/hitmonchan.gif")
        lickitung.setAttribute("src", "./src/imagens/lickitung.gif")
        koffing.setAttribute("src", "./src/imagens/koffing.gif")
        weezing.setAttribute("src", "./src/imagens/weezing.gif")
        rhyhorn.setAttribute("src", "./src/imagens/rhyhorn.gif")
        rhydon.setAttribute("src", "./src/imagens/rhydon.gif")
        chansey.setAttribute("src", "./src/imagens/chansey.gif")
        tangela.setAttribute("src", "./src/imagens/tangela.gif")
        kangaskhan.setAttribute("src", "./src/imagens/kangaskhan.gif")
        horsea.setAttribute("src", "./src/imagens/horsea.gif")
        seadra.setAttribute("src", "./src/imagens/seadra.gif")
        goldeen.setAttribute("src", "./src/imagens/goldeen.gif")
        seaking.setAttribute("src", "./src/imagens/seaking.gif")
        staryu.setAttribute("src", "./src/imagens/staryu.gif")
        starmie.setAttribute("src", "./src/imagens/starmie.gif")
        mrmime.setAttribute("src", "./src/imagens/mr-mime.gif")
        scyther.setAttribute("src", "./src/imagens/scyther.gif")
        jynx.setAttribute("src", "./src/imagens/jynx.gif")
        electabuzz.setAttribute("src", "./src/imagens/electabuzz.gif")
        magmar.setAttribute("src", "./src/imagens/magmar.gif")
        pinsir.setAttribute("src", "./src/imagens/pinsir.gif")
        tauros.setAttribute("src", "./src/imagens/tauros.gif")
        magikarp.setAttribute("src", "./src/imagens/magikarp.gif")
        gyarados.setAttribute("src", "./src/imagens/gyarados.gif")
        lapras.setAttribute("src", "./src/imagens/lapras.gif")
        ditto.setAttribute("src", "./src/imagens/ditto.gif")
        eevee.setAttribute("src", "./src/imagens/eevee.gif")
        vaporeon.setAttribute("src", "./src/imagens/vaporeon.gif")
        jolteon.setAttribute("src", "./src/imagens/jolteon.gif")
        flareon.setAttribute("src", "./src/imagens/flareon.gif")
        porygon.setAttribute("src", "./src/imagens/porygon.gif")
        omanyte.setAttribute("src", "./src/imagens/omanyte.gif")
        omastar.setAttribute("src", "./src/imagens/omastar.gif")
        kabuto.setAttribute("src", "./src/imagens/kabuto.gif")
        kabutops.setAttribute("src", "./src/imagens/kabutops.gif")
        aerodactyl.setAttribute("src", "./src/imagens/aerodactyl.gif")
        snorlax.setAttribute("src", "./src/imagens/snorlax.gif")
        articuno.setAttribute("src", "./src/imagens/articuno.gif")
        zapdos.setAttribute("src", "./src/imagens/zapdos.gif")
        moltres.setAttribute("src", "./src/imagens/moltres.gif")
        dratini.setAttribute("src", "./src/imagens/dratini.gif")
        dragonair.setAttribute("src", "./src/imagens/dragonair.gif")
        dragonite.setAttribute("src", "./src/imagens/dragonite.gif")
        mewtwo.setAttribute("src", "./src/imagens/mewtwo.gif")
        mew.setAttribute("src", "./src/imagens/mew.gif")

    } else {

        imagemBotaoTrocaDeTema.setAttribute("src", "./src/imagens/moon.png")
        imagemPokebola.setAttribute("src", "./src/imagens/greatball.png")
        imagemLogo.setAttribute("src", "./src/imagens/logoModoEscuro.png")

        bulbasaur.setAttribute("src", "./src/imagens/bulbasaur-s.gif")
        ivysaur.setAttribute("src", "./src/imagens/ivysaur-s.gif")
        venusaur.setAttribute("src", "./src/imagens/venusaur-s.gif")
        charmander.setAttribute("src", "./src/imagens/charmander-s.gif")
        charmeleon.setAttribute("src", "./src/imagens/charmeleon-s.gif")
        charizard.setAttribute("src", "./src/imagens/charizard-s.gif")
        squirtle.setAttribute("src", "./src/imagens/squirtle-s.gif")
        wartortle.setAttribute("src", "./src/imagens/wartortle-s.gif")
        blastoise.setAttribute("src", "./src/imagens/blastoise-s.gif")
        caterpie.setAttribute("src", "./src/imagens/caterpie-s.gif")
        metapod.setAttribute("src", "./src/imagens/metapod-s.gif")
        butterfree.setAttribute("src", "./src/imagens/butterfree-s.gif")
        weedle.setAttribute("src", "./src/imagens/weedle-s.gif")
        kakuna.setAttribute("src", "./src/imagens/kakuna-s.gif")
        beedrill.setAttribute("src", "./src/imagens/beedrill-s.gif")
        pidgey.setAttribute("src", "./src/imagens/pidgey-s.gif")
        pidgeotto.setAttribute("src", "./src/imagens/pidgeotto-s.gif")
        pidgeot.setAttribute("src", "./src/imagens/pidgeot-s.gif")
        rattata.setAttribute("src", "./src/imagens/rattata-s.gif")
        raticate.setAttribute("src", "./src/imagens/raticate-s.gif")
        spearow.setAttribute("src", "./src/imagens/spearow-s.gif")
        fearow.setAttribute("src", "./src/imagens/fearow-s.gif")
        ekans.setAttribute("src", "./src/imagens/ekans-s.gif")
        arbok.setAttribute("src", "./src/imagens/arbok-s.gif")
        pikachu.setAttribute("src", "./src/imagens/pikachu-s.gif")
        raichu.setAttribute("src", "./src/imagens/raichu-s.gif")
        sandshrew.setAttribute("src", "./src/imagens/sandshrew-s.gif")
        sandslash.setAttribute("src", "./src/imagens/sandslash-s.gif")
        nidoranfemea.setAttribute("src", "./src/imagens/nidoran-femea-s.gif")
        nidorina.setAttribute("src", "./src/imagens/nidorina-s.gif")
        nidoqueen.setAttribute("src", "./src/imagens/nidoqueen-s.gif")
        nidoranmacho.setAttribute("src", "./src/imagens/nidoran-macho-s.gif")
        nidorino.setAttribute("src", "./src/imagens/nidorino-s.gif")
        nidoking.setAttribute("src", "./src/imagens/nidoking-s.gif")
        clefairy.setAttribute("src", "./src/imagens/clefairy-s.gif")
        clefable.setAttribute("src", "./src/imagens/clefable-s.gif")
        vulpix.setAttribute("src", "./src/imagens/vulpix-s.gif")
        ninetales.setAttribute("src", "./src/imagens/ninetales-s.gif")
        jigglypuff.setAttribute("src", "./src/imagens/jigglypuff-s.gif")
        wigglytuff.setAttribute("src", "./src/imagens/wigglytuff-s.gif")
        zubat.setAttribute("src", "./src/imagens/zubat-s.gif")
        golbat.setAttribute("src", "./src/imagens/golbat-s.gif")
        oddish.setAttribute("src", "./src/imagens/oddish-s.gif")
        gloom.setAttribute("src", "./src/imagens/gloom-s.gif")
        vileplume.setAttribute("src", "./src/imagens/vileplume-s.gif")
        paras.setAttribute("src", "./src/imagens/paras-s.gif")
        parasect.setAttribute("src", "./src/imagens/parasect-s.gif")
        venonat.setAttribute("src", "./src/imagens/venonat-s.gif")
        venomoth.setAttribute("src", "./src/imagens/venomoth-s.gif")
        diglett.setAttribute("src", "./src/imagens/diglett-s.gif")
        dugtrio.setAttribute("src", "./src/imagens/dugtrio-s.gif")
        meowth.setAttribute("src", "./src/imagens/meowth-s.gif")
        persian.setAttribute("src", "./src/imagens/persian-s.gif")
        psyduck.setAttribute("src", "./src/imagens/psyduck-s.gif")
        golduck.setAttribute("src", "./src/imagens/golduck-s.gif")
        mankey.setAttribute("src", "./src/imagens/mankey-s.gif")
        primeape.setAttribute("src", "./src/imagens/primeape-s.gif")
        growlithe.setAttribute("src", "./src/imagens/growlithe-s.gif")
        arcanine.setAttribute("src", "./src/imagens/arcanine-s.gif")
        poliwag.setAttribute("src", "./src/imagens/poliwag-s.gif")
        poliwhirl.setAttribute("src", "./src/imagens/poliwhirl-s.gif")
        poliwrath.setAttribute("src", "./src/imagens/poliwrath-s.gif")
        abra.setAttribute("src", "./src/imagens/abra-s.gif")
        kadabra.setAttribute("src", "./src/imagens/kadabra-s.gif")
        alakazam.setAttribute("src", "./src/imagens/alakazam-s.gif")
        machop.setAttribute("src", "./src/imagens/machop-s.gif")
        machoke.setAttribute("src", "./src/imagens/machoke-s.gif")
        machamp.setAttribute("src", "./src/imagens/machamp-s.gif")
        bellsprout.setAttribute("src", "./src/imagens/bellsprout-s.gif")
        weepinbell.setAttribute("src", "./src/imagens/weepinbell-s.gif")
        victreebel.setAttribute("src", "./src/imagens/victreebel-s.gif")
        tentacool.setAttribute("src", "./src/imagens/tentacool-s.gif")
        tentacruel.setAttribute("src", "./src/imagens/tentacruel-s.gif")
        geodude.setAttribute("src", "./src/imagens/geodude-s.gif")
        graveler.setAttribute("src", "./src/imagens/graveler-s.gif")
        golem.setAttribute("src", "./src/imagens/golem-s.gif")
        ponyta.setAttribute("src", "./src/imagens/ponyta-s.gif")
        rapidash.setAttribute("src", "./src/imagens/rapidash-s.gif")
        slowpoke.setAttribute("src", "./src/imagens/slowpoke-s.gif")
        slowbro.setAttribute("src", "./src/imagens/slowbro-s.gif")
        magnemite.setAttribute("src", "./src/imagens/magnemite-s.gif")
        magneton.setAttribute("src", "./src/imagens/magneton-s.gif")
        farfetchd.setAttribute("src", "./src/imagens/farfetchd-s.gif")
        doduo.setAttribute("src", "./src/imagens/doduo-s.gif")
        dodrio.setAttribute("src", "./src/imagens/dodrio-s.gif")
        seel.setAttribute("src", "./src/imagens/seel-s.gif")
        dewgong.setAttribute("src", "./src/imagens/dewgong-s.gif")
        grimer.setAttribute("src", "./src/imagens/grimer-s.gif")
        muk.setAttribute("src", "./src/imagens/muk-s.gif")
        shellder.setAttribute("src", "./src/imagens/shellder-s.gif")
        cloyster.setAttribute("src", "./src/imagens/cloyster-s.gif")
        gastly.setAttribute("src", "./src/imagens/gastly-s.gif")
        haunter.setAttribute("src", "./src/imagens/haunter-s.gif")
        gengar.setAttribute("src", "./src/imagens/gengar-s.gif")
        onix.setAttribute("src", "./src/imagens/onix-s.gif")
        drowzee.setAttribute("src", "./src/imagens/drowzee-s.gif")
        hypno.setAttribute("src", "./src/imagens/hypno-s.gif")
        krabby.setAttribute("src", "./src/imagens/krabby-s.gif")
        kingler.setAttribute("src", "./src/imagens/kingler-s.gif")
        voltorb.setAttribute("src", "./src/imagens/voltorb-s.gif")
        electrode.setAttribute("src", "./src/imagens/electrode-s.gif")
        exeggcute.setAttribute("src", "./src/imagens/exeggcute-s.gif")
        exeggutor.setAttribute("src", "./src/imagens/exeggutor-s.gif")
        cubone.setAttribute("src", "./src/imagens/cubone-s.gif")
        marowak.setAttribute("src", "./src/imagens/marowak-s.gif")
        hitmonlee.setAttribute("src", "./src/imagens/hitmonlee-s.gif")
        hitmonchan.setAttribute("src", "./src/imagens/hitmonchan-s.gif")
        lickitung.setAttribute("src", "./src/imagens/lickitung-s.gif")
        koffing.setAttribute("src", "./src/imagens/koffing-s.gif")
        weezing.setAttribute("src", "./src/imagens/weezing-s.gif")
        rhyhorn.setAttribute("src", "./src/imagens/rhyhorn-s.gif")
        rhydon.setAttribute("src", "./src/imagens/rhydon-s.gif")
        chansey.setAttribute("src", "./src/imagens/chansey-s.gif")
        tangela.setAttribute("src", "./src/imagens/tangela-s.gif")
        kangaskhan.setAttribute("src", "./src/imagens/kangaskhan-s.gif")
        horsea.setAttribute("src", "./src/imagens/horsea-s.gif")
        seadra.setAttribute("src", "./src/imagens/seadra-s.gif")
        goldeen.setAttribute("src", "./src/imagens/goldeen-s.gif")
        seaking.setAttribute("src", "./src/imagens/seaking-s.gif")
        staryu.setAttribute("src", "./src/imagens/staryu-s.gif")
        starmie.setAttribute("src", "./src/imagens/starmie-s.gif")
        mrmime.setAttribute("src", "./src/imagens/mr-mime-s.gif")
        scyther.setAttribute("src", "./src/imagens/scyther-s.gif")
        jynx.setAttribute("src", "./src/imagens/jynx-s.gif")
        electabuzz.setAttribute("src", "./src/imagens/electabuzz-s.gif")
        magmar.setAttribute("src", "./src/imagens/magmar-s.gif")
        pinsir.setAttribute("src", "./src/imagens/pinsir-s.gif")
        tauros.setAttribute("src", "./src/imagens/tauros-s.gif")
        magikarp.setAttribute("src", "./src/imagens/magikarp-s.gif")
        gyarados.setAttribute("src", "./src/imagens/gyarados-s.gif")
        lapras.setAttribute("src", "./src/imagens/lapras-s.gif")
        ditto.setAttribute("src", "./src/imagens/ditto-s.gif")
        eevee.setAttribute("src", "./src/imagens/eevee-s.gif")
        vaporeon.setAttribute("src", "./src/imagens/vaporeon-s.gif")
        jolteon.setAttribute("src", "./src/imagens/jolteon-s.gif")
        flareon.setAttribute("src", "./src/imagens/flareon-s.gif")
        porygon.setAttribute("src", "./src/imagens/porygon-s.gif")
        omanyte.setAttribute("src", "./src/imagens/omanyte-s.gif")
        omastar.setAttribute("src", "./src/imagens/omastar-s.gif")
        kabuto.setAttribute("src", "./src/imagens/kabuto-s.gif")
        kabutops.setAttribute("src", "./src/imagens/kabutops-s.gif")
        aerodactyl.setAttribute("src", "./src/imagens/aerodactyl-s.gif")
        snorlax.setAttribute("src", "./src/imagens/snorlax-s.gif")
        articuno.setAttribute("src", "./src/imagens/articuno-s.gif")
        zapdos.setAttribute("src", "./src/imagens/zapdos-s.gif")
        moltres.setAttribute("src", "./src/imagens/moltres-s.gif")
        dratini.setAttribute("src", "./src/imagens/dratini-s.gif")
        dragonair.setAttribute("src", "./src/imagens/dragonair-s.gif")
        dragonite.setAttribute("src", "./src/imagens/dragonite-s.gif")
        mewtwo.setAttribute("src", "./src/imagens/mewtwo-s.gif")
        mew.setAttribute("src", "./src/imagens/mew-s.gif")
    }   
    
})


